import type { ApprovalStep } from "~/types";

export const mockApprovals: ApprovalStep[] = [
    {
        "id": 7,
        "loanApplicationId": 1,
        "loanRef": "LN-2026-001",
        "employeeName": "Liam Naguit",
        "requestedAmount": 50000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 8,
        "loanApplicationId": 1,
        "loanRef": "LN-2026-001",
        "employeeName": "Liam Naguit",
        "requestedAmount": 50000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },

    {
        "id": 1,
        "loanApplicationId": 4,
        "loanRef": "LN-2026-004",
        "employeeName": "Amara Okafor",
        "requestedAmount": 15000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 2,
        "loanApplicationId": 4,
        "loanRef": "LN-2026-004",
        "employeeName": "Amara Okafor",
        "requestedAmount": 15000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 3,
        "loanApplicationId": 4,
        "loanRef": "LN-2026-004",
        "employeeName": "Amara Okafor",
        "requestedAmount": 15000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 4,
        "loanApplicationId": 5,
        "loanRef": "LN-2026-005",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 20000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Looks good.",
        "actionDate": "2026-05-20T10:00:00Z"
    },
    {
        "id": 5,
        "loanApplicationId": 5,
        "loanRef": "LN-2026-005",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 20000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 6,
        "loanApplicationId": 5,
        "loanRef": "LN-2026-005",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 20000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 9,
        "loanApplicationId": 7,
        "loanRef": "LN-2026-007",
        "employeeName": "Juan Dela Cruz",
        "requestedAmount": 60000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "OK to proceed.",
        "actionDate": "2026-05-12T10:00:00Z"
    },
    {
        "id": 10,
        "loanApplicationId": 7,
        "loanRef": "LN-2026-007",
        "employeeName": "Juan Dela Cruz",
        "requestedAmount": 60000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Rejected",
        "comments": "Insufficient net pay capacity.",
        "actionDate": "2026-05-13T14:30:00Z"
    },
    {
        "id": 11,
        "loanApplicationId": 8,
        "loanRef": "LN-2026-008",
        "employeeName": "Maria Santos",
        "requestedAmount": 1500000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Approved.",
        "actionDate": "2026-03-07T09:00:00Z"
    },
    {
        "id": 12,
        "loanApplicationId": 8,
        "loanRef": "LN-2026-008",
        "employeeName": "Maria Santos",
        "requestedAmount": 1500000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Approved",
        "comments": "Documents verified.",
        "actionDate": "2026-03-12T10:00:00Z"
    },
    {
        "id": 13,
        "loanApplicationId": 8,
        "loanRef": "LN-2026-008",
        "employeeName": "Maria Santos",
        "requestedAmount": 1500000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": 3,
        "status": "Approved",
        "comments": "Funds ready for disbursement.",
        "actionDate": "2026-03-20T10:00:00Z"
    },
    {
        "id": 14,
        "loanApplicationId": 11,
        "loanRef": "LN-2026-011",
        "employeeName": "Roberto Cruz",
        "requestedAmount": 150000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Recommended for approval.",
        "actionDate": "2026-05-21T09:00:00Z"
    },
    {
        "id": 15,
        "loanApplicationId": 11,
        "loanRef": "LN-2026-011",
        "employeeName": "Roberto Cruz",
        "requestedAmount": 150000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 16,
        "loanApplicationId": 16,
        "loanRef": "LN-2026-016",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 28000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Rejected",
        "comments": "Existing active loan detected. Cannot process concurrent loans.",
        "actionDate": "2026-05-09T10:00:00Z"
    },
    {
        "id": 17,
        "loanApplicationId": 19,
        "loanRef": "LN-2026-019",
        "employeeName": "Dante Ramos",
        "requestedAmount": 300000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 18,
        "loanApplicationId": 19,
        "loanRef": "LN-2026-019",
        "employeeName": "Dante Ramos",
        "requestedAmount": 300000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 2,
        "loanApplicationId": 4,
        "loanRef": "LN-2026-004",
        "employeeName": "Amara Okafor",
        "requestedAmount": 15000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 3,
        "loanApplicationId": 4,
        "loanRef": "LN-2026-004",
        "employeeName": "Amara Okafor",
        "requestedAmount": 15000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 4,
        "loanApplicationId": 5,
        "loanRef": "LN-2026-005",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 20000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Looks good.",
        "actionDate": "2026-05-20T10:00:00Z"
    },
    {
        "id": 5,
        "loanApplicationId": 5,
        "loanRef": "LN-2026-005",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 20000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 6,
        "loanApplicationId": 5,
        "loanRef": "LN-2026-005",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 20000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 9,
        "loanApplicationId": 7,
        "loanRef": "LN-2026-007",
        "employeeName": "Juan Dela Cruz",
        "requestedAmount": 60000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "OK to proceed.",
        "actionDate": "2026-05-12T10:00:00Z"
    },
    {
        "id": 10,
        "loanApplicationId": 7,
        "loanRef": "LN-2026-007",
        "employeeName": "Juan Dela Cruz",
        "requestedAmount": 60000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Rejected",
        "comments": "Insufficient net pay capacity.",
        "actionDate": "2026-05-13T14:30:00Z"
    },
    {
        "id": 11,
        "loanApplicationId": 8,
        "loanRef": "LN-2026-008",
        "employeeName": "Maria Santos",
        "requestedAmount": 1500000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Approved.",
        "actionDate": "2026-03-07T09:00:00Z"
    },
    {
        "id": 12,
        "loanApplicationId": 8,
        "loanRef": "LN-2026-008",
        "employeeName": "Maria Santos",
        "requestedAmount": 1500000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Approved",
        "comments": "Documents verified.",
        "actionDate": "2026-03-12T10:00:00Z"
    },
    {
        "id": 13,
        "loanApplicationId": 8,
        "loanRef": "LN-2026-008",
        "employeeName": "Maria Santos",
        "requestedAmount": 1500000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": 3,
        "status": "Approved",
        "comments": "Funds ready for disbursement.",
        "actionDate": "2026-03-20T10:00:00Z"
    },
    {
        "id": 14,
        "loanApplicationId": 11,
        "loanRef": "LN-2026-011",
        "employeeName": "Roberto Cruz",
        "requestedAmount": 150000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Recommended for approval.",
        "actionDate": "2026-05-21T09:00:00Z"
    },
    {
        "id": 15,
        "loanApplicationId": 11,
        "loanRef": "LN-2026-011",
        "employeeName": "Roberto Cruz",
        "requestedAmount": 150000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 16,
        "loanApplicationId": 16,
        "loanRef": "LN-2026-016",
        "employeeName": "Kenji Tanaka",
        "requestedAmount": 28000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Rejected",
        "comments": "Existing active loan detected. Cannot process concurrent loans.",
        "actionDate": "2026-05-09T10:00:00Z"
    },
    {
        "id": 17,
        "loanApplicationId": 19,
        "loanRef": "LN-2026-019",
        "employeeName": "Dante Ramos",
        "requestedAmount": 300000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 18,
        "loanApplicationId": 19,
        "loanRef": "LN-2026-019",
        "employeeName": "Dante Ramos",
        "requestedAmount": 300000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 19,
        "loanApplicationId": 19,
        "loanRef": "LN-2026-019",
        "employeeName": "Dante Ramos",
        "requestedAmount": 300000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": null,
        "status": "Pending",
        "comments": null,
        "actionDate": null
    },
    {
        "id": 20,
        "loanApplicationId": 9,
        "loanRef": "LN-2026-009",
        "employeeName": "Carlos Mendoza",
        "requestedAmount": 450000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Looks good.",
        "actionDate": "2026-02-12T10:00:00Z"
    },
    {
        "id": 21,
        "loanApplicationId": 9,
        "loanRef": "LN-2026-009",
        "employeeName": "Carlos Mendoza",
        "requestedAmount": 450000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Approved",
        "comments": "Approved by HR.",
        "actionDate": "2026-02-15T14:00:00Z"
    },
    {
        "id": 22,
        "loanApplicationId": 9,
        "loanRef": "LN-2026-009",
        "employeeName": "Carlos Mendoza",
        "requestedAmount": 450000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": 3,
        "status": "Approved",
        "comments": "Ready for check preparation.",
        "actionDate": "2026-02-18T14:00:00Z"
    },
    {
        "id": 23,
        "loanApplicationId": 10,
        "loanRef": "LN-2026-010",
        "employeeName": "Sofia Villanueva",
        "requestedAmount": 80000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Approved.",
        "actionDate": "2026-05-06T09:00:00Z"
    },
    {
        "id": 24,
        "loanApplicationId": 10,
        "loanRef": "LN-2026-010",
        "employeeName": "Sofia Villanueva",
        "requestedAmount": 80000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Approved",
        "comments": "Verified.",
        "actionDate": "2026-05-07T10:00:00Z"
    },
    {
        "id": 25,
        "loanApplicationId": 10,
        "loanRef": "LN-2026-010",
        "employeeName": "Sofia Villanueva",
        "requestedAmount": 80000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": 3,
        "status": "Approved",
        "comments": "Disbursement processed.",
        "actionDate": "2026-05-08T14:00:00Z"
    },
    {
        "id": 26,
        "loanApplicationId": 14,
        "loanRef": "LN-2026-014",
        "employeeName": "Miguel Torres",
        "requestedAmount": 30000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Training is highly recommended.",
        "actionDate": "2026-05-20T09:00:00Z"
    },
    {
        "id": 27,
        "loanApplicationId": 14,
        "loanRef": "LN-2026-014",
        "employeeName": "Miguel Torres",
        "requestedAmount": 30000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Approved",
        "comments": "Certification course verified.",
        "actionDate": "2026-05-20T14:00:00Z"
    },
    {
        "id": 28,
        "loanApplicationId": 14,
        "loanRef": "LN-2026-014",
        "employeeName": "Miguel Torres",
        "requestedAmount": 30000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": 3,
        "status": "Approved",
        "comments": "Pending disbursement scheduling.",
        "actionDate": "2026-05-21T09:00:00Z"
    },
    {
        "id": 29,
        "loanApplicationId": 20,
        "loanRef": "LN-2026-020",
        "employeeName": "Carlos Mendoza",
        "requestedAmount": 250000,
        "stepOrder": 1,
        "role": "Supervisor",
        "approverId": 1,
        "status": "Approved",
        "comments": "Approved.",
        "actionDate": "2024-06-02T10:00:00Z"
    },
    {
        "id": 30,
        "loanApplicationId": 20,
        "loanRef": "LN-2026-020",
        "employeeName": "Carlos Mendoza",
        "requestedAmount": 250000,
        "stepOrder": 2,
        "role": "HR",
        "approverId": 2,
        "status": "Approved",
        "comments": "Verified.",
        "actionDate": "2024-06-03T11:00:00Z"
    },
    {
        "id": 31,
        "loanApplicationId": 20,
        "loanRef": "LN-2026-020",
        "employeeName": "Carlos Mendoza",
        "requestedAmount": 250000,
        "stepOrder": 3,
        "role": "Finance",
        "approverId": 3,
        "status": "Approved",
        "comments": "Disbursement processed.",
        "actionDate": "2024-06-05T10:00:00Z"
    }
];
