import type { LoanType } from "~/types";

export const mockLoanTypes: LoanType[] = [
    {
        "id": 1,
        "name": "Salary Loan",
        "description": "Standard multi-purpose loan based on monthly basic salary.",
        "maxAmount": 100000,
        "minTenureMonths": 6,
        "interestRate": 6,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 24,
        "requiredDocuments": ["Payslip", "Company ID"],
        "isActive": true,
        "activeLoans": 18,
        "totalDisbursed": 3500000,
        "createdAt": "2026-01-10T08:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 2,
        "name": "Emergency Loan",
        "description": "Quick access funds for medical or family emergencies.",
        "maxAmount": 50000,
        "minTenureMonths": 3,
        "interestRate": 3,
        "interestMethod": "flat",
        "maxRepaymentMonths": 12,
        "requiredDocuments": ["Medical Certificate or Proof of Emergency"],
        "isActive": true,
        "activeLoans": 12,
        "totalDisbursed": 1800000,
        "createdAt": "2026-01-15T09:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 3,
        "name": "Calamity Loan",
        "description": "Financial assistance for employees affected by natural disasters.",
        "maxAmount": 50000,
        "minTenureMonths": 1,
        "interestRate": 0,
        "interestMethod": "flat",
        "maxRepaymentMonths": 24,
        "requiredDocuments": ["Barangay Certificate of Calamity", "Photos"],
        "isActive": true,
        "activeLoans": 5,
        "totalDisbursed": 750000,
        "createdAt": "2026-02-01T10:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 4,
        "name": "Equipment Loan",
        "description": "Loan for purchasing work-from-home equipment or laptops.",
        "maxAmount": 150000,
        "minTenureMonths": 6,
        "interestRate": 8,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 36,
        "requiredDocuments": ["Quotation of Equipment"],
        "isActive": true,
        "activeLoans": 7,
        "totalDisbursed": 1900000,
        "createdAt": "2026-03-10T11:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 5,
        "name": "Cash Advance",
        "description": "Short-term advance on next payroll cutoff.",
        "maxAmount": 20000,
        "minTenureMonths": 3,
        "interestRate": 0,
        "interestMethod": "flat",
        "maxRepaymentMonths": 3,
        "requiredDocuments": [],
        "isActive": true,
        "activeLoans": 5,
        "totalDisbursed": 800000,
        "createdAt": "2026-04-05T14:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 6,
        "name": "Housing Loan",
        "description": "Long-term loan for home purchase, construction, or renovation.",
        "maxAmount": 2000000,
        "minTenureMonths": 12,
        "interestRate": 9,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 120,
        "requiredDocuments": ["Land Title", "Tax Declaration", "Floor Plan", "Payslip"],
        "isActive": true,
        "activeLoans": 24,
        "totalDisbursed": 28500000,
        "createdAt": "2026-01-05T08:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 7,
        "name": "Vehicle Loan",
        "description": "Financing for purchase of a brand new or second-hand vehicle.",
        "maxAmount": 800000,
        "minTenureMonths": 12,
        "interestRate": 10,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 60,
        "requiredDocuments": ["OR/CR", "Vehicle Quotation", "Payslip", "Valid ID"],
        "isActive": true,
        "activeLoans": 15,
        "totalDisbursed": 9200000,
        "createdAt": "2026-01-20T09:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 8,
        "name": "Educational Loan",
        "description": "Loan to cover tuition fees and educational expenses for dependents.",
        "maxAmount": 120000,
        "minTenureMonths": 6,
        "interestRate": 4,
        "interestMethod": "flat",
        "maxRepaymentMonths": 24,
        "requiredDocuments": ["Enrollment Form", "Assessment of Fees", "Payslip"],
        "isActive": true,
        "activeLoans": 10,
        "totalDisbursed": 2400000,
        "createdAt": "2026-02-10T10:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 9,
        "name": "Personal Loan",
        "description": "General-purpose loan for personal financial needs.",
        "maxAmount": 200000,
        "minTenureMonths": 6,
        "interestRate": 12,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 48,
        "requiredDocuments": ["Valid ID", "Payslip", "Proof of Billing"],
        "isActive": true,
        "activeLoans": 30,
        "totalDisbursed": 11500000,
        "createdAt": "2026-01-08T08:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 10,
        "name": "Business Loan",
        "description": "Capital assistance for employees running a small side business.",
        "maxAmount": 500000,
        "minTenureMonths": 12,
        "interestRate": 14,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 60,
        "requiredDocuments": ["Business Plan", "DTI/SEC Registration", "Payslip", "Bank Statements"],
        "isActive": true,
        "activeLoans": 9,
        "totalDisbursed": 6300000,
        "createdAt": "2026-02-20T11:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 11,
        "name": "Medical Loan",
        "description": "Covers hospitalization, surgery, and post-operative medical expenses.",
        "maxAmount": 80000,
        "minTenureMonths": 3,
        "interestRate": 2,
        "interestMethod": "flat",
        "maxRepaymentMonths": 18,
        "requiredDocuments": ["Hospital Bill", "Medical Certificate", "PhilHealth Statement"],
        "isActive": true,
        "activeLoans": 8,
        "totalDisbursed": 1200000,
        "createdAt": "2026-03-01T09:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 12,
        "name": "Travel Loan",
        "description": "Loan for vacation, leisure travel, or family trip expenses.",
        "maxAmount": 60000,
        "minTenureMonths": 3,
        "interestRate": 7,
        "interestMethod": "flat",
        "maxRepaymentMonths": 12,
        "requiredDocuments": ["Travel Itinerary", "Valid ID"],
        "isActive": false,
        "activeLoans": 0,
        "totalDisbursed": 540000,
        "createdAt": "2026-03-15T10:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 13,
        "name": "Maternity Loan",
        "description": "Financial support for female employees before and after childbirth.",
        "maxAmount": 40000,
        "minTenureMonths": 1,
        "interestRate": 0,
        "interestMethod": "flat",
        "maxRepaymentMonths": 12,
        "requiredDocuments": ["OB Certificate", "SSS Maternity Benefit Claim"],
        "isActive": true,
        "activeLoans": 4,
        "totalDisbursed": 480000,
        "createdAt": "2026-02-25T08:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 14,
        "name": "Retirement Bridge Loan",
        "description": "Short-term loan for employees nearing retirement to cover transition expenses.",
        "maxAmount": 300000,
        "minTenureMonths": 6,
        "interestRate": 5,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 24,
        "requiredDocuments": ["Retirement Notice", "Service Record", "Payslip"],
        "isActive": true,
        "activeLoans": 3,
        "totalDisbursed": 1500000,
        "createdAt": "2026-03-20T11:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 15,
        "name": "Relocation Loan",
        "description": "Assistance for employees transferring to a new work assignment location.",
        "maxAmount": 75000,
        "minTenureMonths": 3,
        "interestRate": 4,
        "interestMethod": "flat",
        "maxRepaymentMonths": 18,
        "requiredDocuments": ["Transfer Order", "Lease Agreement or Moving Quotation"],
        "isActive": true,
        "activeLoans": 6,
        "totalDisbursed": 900000,
        "createdAt": "2026-04-01T09:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 16,
        "name": "Training & Development Loan",
        "description": "Funding for professional certifications, seminars, and skills training.",
        "maxAmount": 50000,
        "minTenureMonths": 3,
        "interestRate": 3,
        "interestMethod": "flat",
        "maxRepaymentMonths": 12,
        "requiredDocuments": ["Training Program Details", "Official Receipt or Quotation"],
        "isActive": true,
        "activeLoans": 11,
        "totalDisbursed": 1650000,
        "createdAt": "2026-04-10T10:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 17,
        "name": "Cooperative Share Loan",
        "description": "Loan backed by cooperative share capital for member employees.",
        "maxAmount": 250000,
        "minTenureMonths": 12,
        "interestRate": 6,
        "interestMethod": "diminishing",
        "maxRepaymentMonths": 36,
        "requiredDocuments": ["Cooperative Membership Certificate", "Share Capital Statement"],
        "isActive": true,
        "activeLoans": 14,
        "totalDisbursed": 5200000,
        "createdAt": "2026-01-25T08:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 18,
        "name": "Car Repair Loan",
        "description": "Financing for vehicle repair and maintenance costs.",
        "maxAmount": 80000,
        "minTenureMonths": 3,
        "interestRate": 8,
        "interestMethod": "flat",
        "maxRepaymentMonths": 18,
        "requiredDocuments": ["Repair Quotation", "OR/CR of Vehicle"],
        "isActive": false,
        "activeLoans": 0,
        "totalDisbursed": 720000,
        "createdAt": "2026-03-05T09:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 19,
        "name": "Dental Loan",
        "description": "Covers dental procedures including orthodontics, implants, and oral surgery.",
        "maxAmount": 35000,
        "minTenureMonths": 3,
        "interestRate": 2,
        "interestMethod": "flat",
        "maxRepaymentMonths": 12,
        "requiredDocuments": ["Dental Treatment Plan", "Dentist's Certificate"],
        "isActive": true,
        "activeLoans": 9,
        "totalDisbursed": 630000,
        "createdAt": "2026-04-15T11:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    },
    {
        "id": 20,
        "name": "Gadget Loan",
        "description": "Loan for purchasing mobile phones, tablets, and personal gadgets.",
        "maxAmount": 40000,
        "minTenureMonths": 3,
        "interestRate": 5,
        "interestMethod": "flat",
        "maxRepaymentMonths": 12,
        "requiredDocuments": ["Official Receipt or Sales Invoice", "Valid ID"],
        "isActive": true,
        "activeLoans": 16,
        "totalDisbursed": 2100000,
        "createdAt": "2026-04-20T13:00:00Z",
        "updatedAt": "2026-05-21T08:00:00Z"
    }
];

