import type { LoanApplication } from "~/types";

export const mockLoanApplications: LoanApplication[] = [
    {
        "id": 1,
        "loanRef": "LN-2026-001",
        "employeeId": 1,
        "employeeName": "Liam Naguit",
        "loanTypeId": 1,
        "loanType": "Salary Loan",
        "requestedAmount": 50000,
        "approvedAmount": 50000,
        "termMonths": 12,
        "interestRate": 6,
        "monthlyAmortization": 4416.67,
        "status": "Pending",
        "applicationDate": "2026-05-18T08:00:00Z",
        "approvalDate": null,
        "disbursementDate": null,
        "completionDate": null,
        "remarks": null
    },
    {
        "id": 2,
        "loanRef": "LN-2026-002",
        "employeeId": 2,
        "employeeName": "Juan Dela Cruz",
        "loanTypeId": 2,
        "loanType": "Emergency Loan",
        "requestedAmount": 25000,
        "approvedAmount": 25000,
        "termMonths": 6,
        "interestRate": 3,
        "monthlyAmortization": 4291.67,
        "status": "Approved",
        "applicationDate": "2026-05-17T09:30:00Z",
        "approvalDate": "2026-05-19T10:00:00Z",
        "disbursementDate": null,
        "completionDate": null,
        "remarks": "Approved by HR."
    },
    {
        "id": 3,
        "loanRef": "LN-2026-003",
        "employeeId": 3,
        "employeeName": "Ana Reyes",
        "loanTypeId": 3,
        "loanType": "Calamity Loan",
        "requestedAmount": 30000,
        "approvedAmount": 30000,
        "termMonths": 12,
        "interestRate": 0,
        "monthlyAmortization": 2500,
        "status": "Disbursed",
        "applicationDate": "2026-05-15T11:15:00Z",
        "approvalDate": "2026-05-16T14:20:00Z",
        "disbursementDate": "2026-05-18T09:00:00Z",
        "completionDate": null,
        "remarks": "Funds released."
    },
    {
        "id": 4,
        "loanRef": "LN-2026-004",
        "employeeId": 4,
        "employeeName": "Amara Okafor",
        "loanTypeId": 4,
        "loanType": "Equipment Loan",
        "requestedAmount": 75000,
        "approvedAmount": null,
        "termMonths": 24,
        "interestRate": 8,
        "monthlyAmortization": 3500,
        "status": "Under Review",
        "applicationDate": "2026-05-14T13:45:00Z",
        "approvalDate": null,
        "disbursementDate": null,
        "completionDate": null,
        "remarks": "Pending quotation validation."
    },
    {
        "id": 5,
        "loanRef": "LN-2026-005",
        "employeeId": 5,
        "employeeName": "Kenji Tanaka",
        "loanTypeId": 1,
        "loanType": "Salary Loan",
        "requestedAmount": 40000,
        "approvedAmount": 40000,
        "termMonths": 12,
        "interestRate": 6,
        "monthlyAmortization": 3533.33,
        "status": "Approved",
        "applicationDate": "2026-05-13T16:00:00Z",
        "approvalDate": "2026-05-15T10:30:00Z",
        "disbursementDate": null,
        "completionDate": null,
        "remarks": "Awaiting finance disbursement."
    },
    {
        "id": 6,
        "loanRef": "LN-2026-006",
        "employeeId": 1,
        "employeeName": "Liam Naguit",
        "loanTypeId": 5,
        "loanType": "Cash Advance",
        "requestedAmount": 10000,
        "approvedAmount": 10000,
        "termMonths": 3,
        "interestRate": 0,
        "monthlyAmortization": 3333.33,
        "status": "Active",
        "applicationDate": "2026-04-12T09:00:00Z",
        "approvalDate": "2026-04-13T11:00:00Z",
        "disbursementDate": "2026-04-14T15:00:00Z",
        "completionDate": null,
        "remarks": "Deductions ongoing."
    },
    {
        "id": 7,
        "loanRef": "LN-2026-007",
        "employeeId": 2,
        "employeeName": "Juan Dela Cruz",
        "loanTypeId": 1,
        "loanType": "Salary Loan",
        "requestedAmount": 60000,
        "approvedAmount": null,
        "termMonths": 18,
        "interestRate": 6,
        "monthlyAmortization": null,
        "status": "Rejected",
        "applicationDate": "2026-05-11T14:30:00Z",
        "approvalDate": null,
        "disbursementDate": null,
        "completionDate": null,
        "remarks": "Insufficient net pay capacity."
    }
]
;
